"""initial migration

Revision ID: 8dcb7fc1ae69
Revises: 
Create Date: 2026-02-14 02:08:13.503141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcb7fc1ae69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_ticker'), ['ticker'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'fiscal_date', 'period', name='uix_ticker_fiscal_period')
    )
    with op.batch_alter_table('financials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financials_ticker_id'), ['ticker_id'], unique=False)

    op.create_table('stock_prices',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'ticker_id')
    )
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_prices_ticker_id'), ['ticker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_prices_timestamp'), ['timestamp'], unique=False)

    # Convert to hypertable (TimescaleDB specific)
    # Ensure this only runs on PostgreSQL with TimescaleDB extension
    conn = op.get_bind()
    if conn.dialect.name == 'postgresql':
        op.execute("SELECT create_hypertable('stock_prices', 'timestamp', if_not_exists => TRUE);")

    op.create_table('watchlists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'stock_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    with op.batch_alter_table('stock_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_prices_timestamp'))
        batch_op.drop_index(batch_op.f('ix_stock_prices_ticker_id'))

    op.drop_table('stock_prices')
    with op.batch_alter_table('financials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financials_ticker_id'))

    op.drop_table('financials')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_ticker'))

    op.drop_table('stocks')
    # ### end Alembic commands ###
